# Generated by Django 5.1.5 on 2025-03-01 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_review_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='destination',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
    ]
