# Generated by Django 5.1.5 on 2025-03-01 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_destination_latitude_destination_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('boating', 'Boating'), ('kayaking', 'Kayaking'), ('trekking', 'Trekking'), ('sightseeing', 'Sightseeing'), ('camping', 'Camping'), ('adventure', 'Adventure'), ('hiking', 'Hiking'), ('diving', 'Diving')], max_length=100),
        ),
    ]
